Repository qiskit-community/qiskit-experiments, pull requests merged in 2022-05, with the labels that each got.

#615 API documentation guideline
  CONTRIBUTING.md
  docs/_ext/custom_styles/example/__init__.py
  docs/_ext/custom_styles/example/example_experiment.py
Labels: documentation

#801 Level2 memory
  qiskit_experiments/framework/composite/composite_analysis.py
  releasenotes/notes/marginalization-da56f76045f7736f.yaml
  test/test_composite.py
Labels: backport stable potential, Changelog: Bugfix

#794 CR Hamiltonian experiment without cr_gate
  qiskit_experiments/library/characterization/cr_hamiltonian.py
  releasenotes/notes/fix-instantiate-crhamtomo-without-crgate-1b5bdd957b9fad69.yaml
  test/test_cross_resonance_hamiltonian.py
Labels: backport stable potential, Changelog: Bugfix

#804 Fix curve analysis multi-canvas plotting
  qiskit_experiments/curve_analysis/curve_analysis.py
  releasenotes/notes/fix-multi-series-plot-ac5ff39cabf5d578.yaml
Labels: backport stable potential, Changelog: Bugfix

#786 Updated contributing guide
  CONTRIBUTING.md
Labels: documentation

#810 Mark support for for Python 3.10 and add test jobs
  .github/workflows/main.yml
  setup.py
Labels: backport stable potential, Changelog: None
