Repository qiskit-community/qiskit-experiments, pull requests merged in 2022-02, with the labels that each got.

#633 Update CompositeAnalysis initialization
  qiskit_experiments/framework/composite/composite_analysis.py
  qiskit_experiments/framework/composite/composite_experiment.py
  releasenotes/notes/composite-analysis-c3119d5d2e64ce78.yaml
  test/test_composite.py
  test/test_tomography.py
Labels: Changelog: API Change

#645 Fix bug in BaseAnalysis.from_config
  qiskit_experiments/framework/base_analysis.py
  test/test_framework.py
Labels: Changelog: Bugfix

#657 Fix CompositeExperiment.copy to preserve analysis referances
  qiskit_experiments/framework/base_experiment.py
  qiskit_experiments/framework/composite/composite_analysis.py
  qiskit_experiments/framework/composite/composite_experiment.py
  releasenotes/notes/fix-composite-copy-a869e9773f6a4d48.yaml
  test/test_composite.py
Labels: Changelog: Bugfix

#660 Fix missing confidence interval in the output figure.
  docs/tutorials/randomized_benchmarking.ipynb
  docs/tutorials/t1.ipynb
  docs/tutorials/t2hahn_characterization.ipynb
  docs/tutorials/t2ramsey_characterization.ipynb
  qiskit_experiments/curve_analysis/visualization/curves.py
  qiskit_experiments/curve_analysis/visualization/fit_result_plotters.py
  qiskit_experiments/curve_analysis/visualization/style.py
Labels: Changelog: Bugfix

#604 Make ExperimentData serializable
  qiskit_experiments/database_service/db_analysis_result.py
  qiskit_experiments/database_service/db_experiment_data.py
  qiskit_experiments/database_service/device_component.py
  qiskit_experiments/database_service/utils.py
  qiskit_experiments/framework/experiment_data.py
  qiskit_experiments/library/tomography/basis/base_basis.py
  qiskit_experiments/test/mock_iq_backend.py
  qiskit_experiments/test/t1_backend.py
  qiskit_experiments/test/t2hahn_backend.py
  qiskit_experiments/test/t2ramsey_backend.py
  qiskit_experiments/test/tphi_backend.py
  qiskit_experiments/test/utils.py
  releasenotes/notes/serialize-expdata-47ad38c94bf479e1.yaml
  test/base.py
  test/randomized_benchmarking/test_randomized_benchmarking.py
  test/test_t1.py
  test/test_t2hahn.py
  test/test_t2ramsey.py
  test/test_tomography.py
  test/test_tphi.py
Labels: Changelog: New Feature
