Repository qiskit-community/qiskit-experiments, pull requests merged in 2022-03, with the labels that each got.

#701 Add `BaseExperiment._finalize` method
  qiskit_experiments/framework/base_experiment.py
  qiskit_experiments/framework/composite/composite_experiment.py
  releasenotes/notes/exp-finalize-b7ca0a139ad5f872.yaml
  test/test_composite.py
Labels: Changelog: New Feature

#711 Fix QuantumVolumeAnalysis
  qiskit_experiments/library/quantum_volume/qv_analysis.py
Labels: Changelog: Bugfix

#628 Issue template for adding a new experiment
  .github/ISSUE_TEMPLATE/NEW_EXPERIMENT.md
Labels: needs review

#730 Fix tomography fitter data
  qiskit_experiments/library/tomography/fitters/cvxpy_lstsq.py
  qiskit_experiments/library/tomography/fitters/fitter_utils.py
  qiskit_experiments/library/tomography/fitters/lininv.py
  qiskit_experiments/library/tomography/fitters/scipy_lstsq.py
  qiskit_experiments/library/tomography/tomography_analysis.py
  releasenotes/notes/fix-tomography-fitter-b144c0df24c30d68.yaml
  requirements-dev.txt
  test/test_tomography.py
Labels: Changelog: Bugfix
