Repository qiskit-community/qiskit-experiments, pull requests merged in 2023-09, with the labels that each got.

#1264 Removed test_t1_parallel_different_analysis_options
  test/library/characterization/test_t1.py
Labels: backport stable potential

#1267 Address timing dependence in ExperimentData.add_jobs test
  test/database_service/test_db_experiment_data.py
Labels: Changelog: None

#1274 Replace deprecated mpl function in visualization test
  test/visualization/test_plotter_mpldrawer.py
Labels: Changelog: Bugfix
