Repository qiskit-community/qiskit-experiments, pull requests merged in 2023-04, with the labels that each got.

#1127 Bump `qiskit-sphinx-theme` version
  .github/workflows/docs_dev.yml
  requirements-dev.txt
Labels: backport stable potential

#1113 Fix MarkerStyle for matplotlib compatibility
  qiskit_experiments/curve_analysis/visualization/mpl_drawer.py
  releasenotes/notes/matplotlib-fix-58d938b49771cf17.yaml
Labels: backport stable potential, Changelog: Bugfix

#1140 Remove current release from previous releases list
  docs/conf.py
Labels: documentation, backport stable potential

#1147 Update release notes and documentation
  README.md
  qiskit_experiments/calibration_management/basis_gate_library.py
  qiskit_experiments/library/__init__.py
  qiskit_experiments/library/calibration/__init__.py
  qiskit_experiments/library/calibration/rough_amplitude_cal.py
  qiskit_experiments/library/calibration/rough_drag_cal.py
  qiskit_experiments/library/calibration/rough_frequency.py
  qiskit_experiments/library/characterization/fine_drag.py
  qiskit_experiments/library/characterization/rabi.py
  releasenotes/notes/backend-in-rough-frequency-cal-8582610249e2327b.yaml
  setup.py
  test/fake_experiment.py
Labels: backport stable potential

#1154 Update citation
  CITATION.cff
  README.md
Labels: documentation

#1156 Pin ipython version
  requirements-dev.txt
Labels: backport stable potential
