Repository qiskit-community/qiskit-experiments, pull requests merged in 2023-05, with the labels that each got.

#1160 Attach calibrations for gates used in calibration experiments
  qiskit_experiments/calibration_management/calibrations.py
  qiskit_experiments/library/calibration/fine_drag_cal.py
  qiskit_experiments/library/calibration/rough_amplitude_cal.py
  releasenotes/notes/attach-other-cals-2f539e7799ceb6c8.yaml
Labels: backport stable potential, Changelog: Bugfix

#1157 Update calibration tests to test _transpiled_circuits
  test/library/calibration/test_drag.py
  test/library/calibration/test_fine_amplitude.py
  test/library/calibration/test_fine_drag.py
  test/library/calibration/test_rough_amplitude.py
Labels: backport stable potential, Changelog: None

#1144 Use marginal_distribution() instead of marginal_counts()
  qiskit_experiments/framework/composite/composite_analysis.py
  qiskit_experiments/library/characterization/analysis/local_readout_error_analysis.py
  qiskit_experiments/library/tomography/fitters/fitter_data.py
Labels: backport stable potential

#1173 Added experiment timestamp how-to
  docs/howtos/experiment_times.rst
  qiskit_experiments/framework/experiment_data.py
Labels: documentation

#1188 Upgrade to Sphinx 6
  .github/workflows/docs.yml
  .github/workflows/docs_dev.yml
  CONTRIBUTING.md
  docs/_static/no_image.png
  docs/conf.py
  pyproject.toml
  requirements-dev.txt
  tox.ini
Labels: documentation
